print('====== DESAFIO 02 ======')
print('Qual sua data de nascimento? ')
dia = input('Dia = ')
mes = input('Mês = ')
ano = input('Ano = ')
print('Você nasceu no', dia, 'de', mes, 'de', ano, '.', 'Correto?')
